[CHRs]
CHR1 ansible_host=10.0.0.2 router_id=1.1.1.1
CHR2 ansible_host=10.0.0.3 router_id=2.2.2.2

[CHR:vars]
ansible_user=admin
ansible_password=admin
ansible_connection=network_cli
ansible_network_os=routeros
